{% set name = "cygrid" %}
{% set version = "2.0.4" %}
{% set sha256 = "ebc49f8ff3cd2c0363783e261825a3e6b948374703be56289f0937e11af4456a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<=37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - compilers  # [osx]
    - llvm-openmp  # [osx]
    - python
    - pip
    - setuptools
    - setuptools_scm
    - extension-helpers
    - astropy
    - cython
    - numpy

  run:
    - python
    - compilers  # [osx]
    - llvm-openmp  # [osx]
    - astropy
    - pytest
    - pytest-astropy
    - pytest-doctestplus
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cygrid

  commands: python -c "import cygrid; cygrid.test()"

about:
  home: https://github.com/bwinkel/{{ name }}
  license: GPL-3.0
  license_family: GPL
  license_file: licenses/README.rst
  summary: Cygrid is a cython-powered convolution-based gridding module for astronomy
  description: |
    Cygrid allows to resample a number of spectra (or data points) to a
    regular grid - a data cube - using any valid astronomical FITS/WCS
    projection. The method is a based on serialized convolution with finite
    gridding kernels. Currently, only Gaussian (radial-symmetric or
    elliptical) kernels are provided (which has the drawback of slight
    degradation of the effective resolution). The algorithm has very small
    memory footprint, allows easy parallelization, and is very fast.
  dev_url: https://github.com/bwinkel/{{ name }}

extra:
  recipe-maintainers:
    - bwinkel
    - DanielLenz
