travis:
  secure:
    BINSTAR_TOKEN: SMsyowhwoZz3r/7758+AnU0bRRy6rKR8psbQBaooFNSkjS/jmx2LV12m+NKqIAZY5pzx6L5FYiR5MMYGqZPvhbpaflvPAzGzlj089BDYjK4O/efJgP4KD8goPOuRzawtVqP7d1sLrwTh8XIe/P9uw63EIP7EcJUy3JwO7W8boitlbPI+fw7sV9Vo4Zmopp768fOwXHOhka6eEgJJOLDLuK7SF3fiZ20p17fKB7nNlDirTFCc/k+xpTaxbV8kSwKxE7lgaWTk3En5/XmZm/4mGnf7nA2BIwRUpP8doT4tnWkNKrcRF5fP8AB3PIO6xRQlhgycaL9ArXdGr7m2SjCIaeQeqMOWm8WAcITJPK9dJAxT1hCsF/cA+ezFkiEHtBur04p5cO4tzK8jz1vej35hf5156bGnaLqdE8l6fvUwKd5cY8vyjnu/wpgMXwIOKDDpmcGOCRMv86+DLAzG+ZIWaZjtUuqz0e6jT0+fcKKUX8e2a1m2ya8QgPswsQSRHYe97RMYil7atmHkMhsN65EC0uC60NGwQRlazteCRMjpxPQVXJpBNYpygqLHe7R3vzxJJrE7ApxvvMaXUenT/P9Zsl24rQB+9GQCIITGatVspZJLUiKtX5M/n9iHrEI7VH5Jny2k4/KbUnkamUrOzNm/cjrZgkdgkjkvZ21OLIE9zKM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
